---
- name: restart ntp
  service: name=ntp state=restarted
  sudo: yes

- name: force ntp update
  shell: "service ntp stop && ntpdate ntp.ubuntu.com 0.nl.pool.ntp.org && service ntp start"
  sudo: yes

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
  sudo: yes
