---

php:
  packages:
    - php5-sqlite
    - php5-redis
    - php5-mysql
    - php5-imagick
    - php5-gd
    - php5-curl
    - php-pear
    - php5-dev
    - libyaml-dev
    - php5-oauth
  pear:
    - yaml
    - igbinary

  ini:
    global:
      - setting: date.timezone
        value: Europe/Amsterdam
    cli: []
    fpm:
      - setting: memory_limit
        value: 512M
      - setting: upload_max_filesize
        value: 20M
      - setting: post_max_size
        value: 20M
