---

- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/php5-5.6
  tags:
    - php


- name: Update apt
  sudo: yes
  apt: update_cache=yes
  tags:
    - php

- name: Install php5
  sudo: yes
  apt: pkg=php5 state=latest
  tags:
    - php

- name: Install php5-fpm
  apt: name=php5-fpm state=latest
  sudo: yes
  tags:
    - php

- name: Install php packages
  apt: name='{{ item }}' state=latest
  sudo: yes
  with_items: php.packages
  notify:
    - restart php-fpm
  tags:
    - php